<a href="https://colab.research.google.com/github/r2x4/aprendiendo_machine/blob/main/machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  

----
# <center><font color="#615FFF" size="8"> Practice Machine Learning </font></center>
----

In [132]:
# llamar datos
import pandas as pd

datos = pd.read_csv('/content/realistic_drug_labels_side_effects.csv')

In [133]:
datos.shape

(1436, 15)

In [134]:
datos.sample(4)

drug_name     manufacturer  approval_year      drug_class  \
871    Virazole57      Novartis AG           2005     Antipyretic   
357   Cefprofen67           Sanofi           2018       Antiviral   
794  Loxocillin70         Bayer AG           2006         Vaccine   
16      Cefzole42  GlaxoSmithKline           1996  Antidepressant   

           indications                    side_effects  dosage_mg  \
871   Viral infections                        Insomnia        460   
357  Psychosis control  Diarrhea, Blurred vision, Rash        790   
794     Allergy relief     Nausea, Dizziness, Diarrhea        700   
16         Pain relief                  Blurred vision        770   

    administration_route  contraindications                     warnings  \
871          Intravenous  Kidney impairment     Do not operate machinery   
357        Intramuscular             Asthma     Do not operate machinery   
794        Intramuscular      Heart disease  Use with caution in elderly   
16                Rectal             Asthma               Take with food   

     price_usd batch_number expiry_date side_effect_severity approval_status  
871     150.44      Pi317tQ  2027-06-01                 Mild        Rejected  
357     379.73      Tm972Rm  2028-03-25                 Mild        Approved  
794      15.47      EE953TA  2028-06-30                 Mild         Pending  
16       85.40      JW654ck  2027-06-07               Severe        Rejected

In [135]:
datos.columns

Index(['drug_name', 'manufacturer', 'approval_year', 'drug_class',
       'indications', 'side_effects', 'dosage_mg', 'administration_route',
       'contraindications', 'warnings', 'price_usd', 'batch_number',
       'expiry_date', 'side_effect_severity', 'approval_status'],
      dtype='object')

In [136]:
# renombrar la columnas

datos.columns = [
    "nombre_medicamento",
    "fabricante",
    "año_aprobación",
    "clase_medicamento",
    "indicaciones",
    "efectos_secundarios",
    "dosis_mg",
    "vía_administración",
    "contraindicaciones",
    "advertencias",
    "precio_usd",
    "número_lote",
    "fecha_caducidad",
    "gravedad_efectos_secundarios",
    "estado_aprobación"
]

In [137]:
datos.sample(4)

nombre_medicamento       fabricante  año_aprobación clase_medicamento  \
68         Seroprofen18  GlaxoSmithKline            2008        Antifungal   
758        Seroxetine66      Novartis AG            1998     Antihistamine   
660           Viramab50      Merck & Co.            2018        Antibiotic   
1106       Daxodipine39      Pfizer Inc.            2009         Antiviral   

                    indicaciones                   efectos_secundarios  \
68             Fungal infections        Rash, Insomnia, Blurred vision   
758   Prevent infectious disease                               Fatigue   
660                  Pain relief  Dizziness, Dry mouth, Blurred vision   
1106           Fungal infections                     Nausea, Dizziness   

      dosis_mg vía_administración   contraindicaciones  \
68         260      Intramuscular        Liver disease   
758        790      Intramuscular    Allergic reaction   
660        770      Intramuscular  High blood pressure   
1106       820      Intramuscular             Diabetes   

                     advertencias  precio_usd número_lote fecha_caducidad  \
68           May affect fertility      326.32     qn458mn      2026-05-02   
758          May affect fertility      132.13     zW259Kw      2028-01-29   
660   Use with caution in elderly      129.75     og199ZY      2027-04-02   
1106       Monitor blood pressure      150.32     MD697qg      2027-06-08   

     gravedad_efectos_secundarios estado_aprobación  
68                           Mild           Pending  
758                        Severe           Pending  
660                          Mild          Rejected  
1106                     Moderate          Approved

In [138]:
# exportar a csv

datos.to_csv('datos.csv')

In [139]:
# llamar la nueva base

data = pd.read_csv('/content/datos.csv')

In [140]:
data.sample(4)

Unnamed: 0 nombre_medicamento            fabricante  año_aprobación  \
433         433         Zylozole29  Moderna Therapeutics            2023   
241         241          Seromab81           AstraZeneca            1995   
610         610          Mecomab24              Bayer AG            2024   
201         201       Mecostatin56              Bayer AG            2020   

    clase_medicamento          indicaciones             efectos_secundarios  \
433        Antifungal  Depression treatment          Constipation, Insomnia   
241     Antipsychotic  Depression treatment  Dizziness, Dry mouth, Headache   
610         Antiviral  Bacterial infections                Headache, Nausea   
201       Antipyretic      Viral infections                  Blurred vision   

     dosis_mg vía_administración   contraindicaciones          advertencias  \
433       580               Oral        Heart disease     Risk of addiction   
241       320            Topical    Allergic reaction        Take with food   
610       560               Oral  High blood pressure         Avoid alcohol   
201       370      Intramuscular        Liver disease  May affect fertility   

     precio_usd número_lote fecha_caducidad gravedad_efectos_secundarios  \
433       51.17     rV525CM      2025-12-19                       Severe   
241      344.36     SP142vk      2026-02-17                       Severe   
610       26.89     Zd088Tb      2026-07-01                     Moderate   
201        5.72     yX620SW      2028-05-08                         Mild   

    estado_aprobación  
433          Approved  
241          Approved  
610          Approved  
201           Pending

In [141]:
# eliminar una columna

data = data.drop('Unnamed: 0', axis=1)

In [142]:
data.sample(4)

nombre_medicamento            fabricante  año_aprobación  \
1110         Daxozole55              Bayer AG            2000   
1142         Fenozole12     Johnson & Johnson            1995   
524         Daxozepam74           Pfizer Inc.            2004   
786          Rivazole30  Moderna Therapeutics            2021   

      clase_medicamento       indicaciones            efectos_secundarios  \
1110  Anti-inflammatory    Fever reduction             Fatigue, Dizziness   
1142      Antihistamine  Fungal infections  Headache, Dizziness, Diarrhea   
524          Antibiotic  Fungal infections            Insomnia, Dry mouth   
786             Vaccine   Viral infections   Insomnia, Diarrhea, Headache   

      dosis_mg vía_administración  contraindicaciones  \
1110       500         Inhalation   Allergic reaction   
1142       620         Inhalation  Bleeding disorders   
524        130             Rectal   Kidney impairment   
786        980         Sublingual       Liver disease   

                  advertencias  precio_usd número_lote fecha_caducidad  \
1110    Monitor blood pressure      270.42     al896Uw      2028-05-26   
1142    Monitor blood pressure      191.01     YU996IQ      2027-03-22   
524   Do not operate machinery       79.54     zA911Dg      2027-09-07   
786   Do not operate machinery      144.28     XL375dC      2025-11-23   

     gravedad_efectos_secundarios estado_aprobación  
1110                         Mild          Rejected  
1142                     Moderate          Rejected  
524                          Mild          Rejected  
786                      Moderate           Pending

In [143]:
data.dtypes

nombre_medicamento               object
fabricante                       object
año_aprobación                    int64
clase_medicamento                object
indicaciones                     object
efectos_secundarios              object
dosis_mg                          int64
vía_administración               object
contraindicaciones               object
advertencias                     object
precio_usd                      float64
número_lote                      object
fecha_caducidad                  object
gravedad_efectos_secundarios     object
estado_aprobación                object
dtype: object

In [144]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   nombre_medicamento            1436 non-null   object 
 1   fabricante                    1436 non-null   object 
 2   año_aprobación                1436 non-null   int64  
 3   clase_medicamento             1436 non-null   object 
 4   indicaciones                  1436 non-null   object 
 5   efectos_secundarios           1436 non-null   object 
 6   dosis_mg                      1436 non-null   int64  
 7   vía_administración            1436 non-null   object 
 8   contraindicaciones            1436 non-null   object 
 9   advertencias                  1436 non-null   object 
 10  precio_usd                    1436 non-null   float64
 11  número_lote                   1436 non-null   object 
 12  fecha_caducidad               1436 non-null   object 
 13  gra

In [145]:
data.isnull().sum()

nombre_medicamento              0
fabricante                      0
año_aprobación                  0
clase_medicamento               0
indicaciones                    0
efectos_secundarios             0
dosis_mg                        0
vía_administración              0
contraindicaciones              0
advertencias                    0
precio_usd                      0
número_lote                     0
fecha_caducidad                 0
gravedad_efectos_secundarios    0
estado_aprobación               0
dtype: int64

In [146]:
data.duplicated().sum()

np.int64(0)

In [147]:
data.describe()

año_aprobación     dosis_mg   precio_usd
count     1436.000000  1436.000000  1436.000000
mean      2006.860028   509.637883   251.844854
std         10.167067   286.417268   142.640781
min       1990.000000    10.000000     1.210000
25%       1998.000000   270.000000   128.830000
50%       2007.000000   515.000000   255.130000
75%       2016.000000   760.000000   372.207500
max       2024.000000   990.000000   499.060000

#  

---
# <center><Font Color="#615FFF" size="8"> Preparando Datos</Font> </center>
---

In [148]:
# biblioteca

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [149]:
# hecer copia profunda del dataframe
import copy
datos_ml = copy.deepcopy(data)

In [150]:
# eliminar columnas

datos_ml = datos_ml.drop(columns=['número_lote', 'fecha_caducidad'])

In [151]:
datos_ml.head(2)

nombre_medicamento   fabricante  año_aprobación clase_medicamento  \
0       Seroxetine50  AstraZeneca            1996    Antidepressant   
1        Mecoparin93  AstraZeneca            2018           Vaccine   

     indicaciones efectos_secundarios  dosis_mg vía_administración  \
0  Allergy relief     Fatigue, Nausea       260             Rectal   
1  Allergy relief              Nausea       470         Inhalation   

   contraindicaciones    advertencias  precio_usd  \
0  Bleeding disorders   Avoid alcohol      192.43   
1   Allergic reaction  Take with food      397.82   

  gravedad_efectos_secundarios estado_aprobación  
0                         Mild           Pending  
1                         Mild          Approved

In [152]:
# variables para machine

X = datos_ml.drop(columns=['estado_aprobación'])
y = datos_ml['estado_aprobación']

In [153]:
X = pd.get_dummies(X)

In [154]:
# dividir la prueba
X,X_test,y,y_test = train_test_split(X,y,test_size=0.15,stratify=y,random_state=5)
X_train,X_val,y_train,y_val = train_test_split(X,y,stratify=y,random_state=5)


In [155]:
modelo = RandomForestClassifier(random_state=42,max_depth=5)
modelo.fit(X_train, y_train)
print(f'La precisión del modelo train es de : {modelo.score(X_train, y_train)}')
print(f'La precisión del modelo de validacion es de : {modelo.score(X_val, y_val)}')

La precisión del modelo train es de : 0.6032786885245902
La precisión del modelo de validacion es de : 0.3442622950819672


In [156]:
y_pred = modelo.predict(X_test)

In [157]:
# Evaluación
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nReporte de Clasificación:\n", classification_report(y_test, y_pred))
print("\nMatriz de Confusión:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.33796296296296297

Reporte de Clasificación:
               precision    recall  f1-score   support

    Approved       0.38      0.12      0.18        69
     Pending       0.33      0.68      0.44        75
    Rejected       0.35      0.19      0.25        72

    accuracy                           0.34       216
   macro avg       0.35      0.33      0.29       216
weighted avg       0.35      0.34      0.29       216


Matriz de Confusión:
 [[ 8 50 11]
 [ 9 51 15]
 [ 4 54 14]]
