<a href="https://colab.research.google.com/github/r2x4/aprendiendo_machine/blob/main/machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  

----
# <center><font color="#615FFF" size="8"> Practice Machine Learning </font></center>
----

In [597]:
# llamar datos
import pandas as pd

datos = pd.read_csv('/content/realistic_drug_labels_side_effects.csv')

In [598]:
datos.shape

(1436, 15)

In [599]:
datos.sample(4)

drug_name          manufacturer  approval_year      drug_class  \
1235  Virastatin84           AstraZeneca           1990  Antidepressant   
1169   Cefcillin76           Pfizer Inc.           1994   Antipsychotic   
536   Viraprofen90  Moderna Therapeutics           2004   Antihistamine   
1334   Serozepam64           Pfizer Inc.           2013   Antihistamine   

                 indications                 side_effects  dosage_mg  \
1235  Inflammation reduction    Blurred vision, Dry mouth        550   
1169       Fungal infections               Rash, Diarrhea        600   
536     Depression treatment         Dizziness, Dry mouth        740   
1334        Viral infections  Nausea, Dry mouth, Diarrhea        230   

     administration_route contraindications                     warnings  \
1235          Intravenous     Liver disease  Use with caution in elderly   
1169        Intramuscular         Pregnancy            Risk of addiction   
536            Inhalation     Heart disease     Do not operate machinery   
1334              Topical         Pregnancy         May affect fertility   

      price_usd batch_number expiry_date side_effect_severity approval_status  
1235     456.34      Le307Xy  2025-09-02             Moderate        Approved  
1169     495.27      oC837qe  2025-12-18                 Mild        Rejected  
536      332.72      mh640ul  2027-10-01                 Mild        Rejected  
1334       4.97      oD862yn  2028-02-04               Severe        Approved

In [600]:
datos.columns

Index(['drug_name', 'manufacturer', 'approval_year', 'drug_class',
       'indications', 'side_effects', 'dosage_mg', 'administration_route',
       'contraindications', 'warnings', 'price_usd', 'batch_number',
       'expiry_date', 'side_effect_severity', 'approval_status'],
      dtype='object')

In [601]:
# renombrar la columnas

datos.columns = [
    "nombre_medicamento",
    "fabricante",
    "año_aprobación",
    "clase_medicamento",
    "indicaciones",
    "efectos_secundarios",
    "dosis_mg",
    "vía_administración",
    "contraindicaciones",
    "advertencias",
    "precio_usd",
    "número_lote",
    "fecha_caducidad",
    "gravedad_efectos_secundarios",
    "estado_aprobación"
]

In [602]:
datos.sample(4)

nombre_medicamento         fabricante  año_aprobación clase_medicamento  \
241          Seromab81        AstraZeneca            1995     Antipsychotic   
762       Zylocillin36  Johnson & Johnson            2013        Antibiotic   
138       Daxoxetine11           Bayer AG            2011     Antipsychotic   
331        Serozepam71           Bayer AG            2007    Antidepressant   

             indicaciones                 efectos_secundarios  dosis_mg  \
241  Depression treatment      Dizziness, Dry mouth, Headache       320   
762       Fever reduction                      Blurred vision       220   
138           Pain relief  Rash, Constipation, Blurred vision        70   
331        Allergy relief                           Dry mouth        50   

    vía_administración contraindicaciones                 advertencias  \
241            Topical  Allergic reaction               Take with food   
762             Rectal      Heart disease       Monitor blood pressure   
138      Intramuscular           Seizures               Take with food   
331             Rectal  Allergic reaction  Use with caution in elderly   

     precio_usd número_lote fecha_caducidad gravedad_efectos_secundarios  \
241      344.36     SP142vk      2026-02-17                       Severe   
762      175.91     km588qR      2025-12-05                         Mild   
138      377.24     tK255Jv      2028-02-23                         Mild   
331      471.31     NJ955QO      2026-11-29                         Mild   

    estado_aprobación  
241          Approved  
762          Approved  
138          Rejected  
331          Approved

In [603]:
# exportar a csv

datos.to_csv('datos.csv')

In [604]:
# llamar la nueva base

data = pd.read_csv('/content/datos.csv')

In [605]:
data.sample(4)

Unnamed: 0 nombre_medicamento         fabricante  año_aprobación  \
580          580        Cefprofen72        AstraZeneca            2001   
792          792       Mecodipine48    GlaxoSmithKline            2023   
1362        1362       Amoxstatin49        Merck & Co.            1994   
1118        1118        Cefprofen77  Johnson & Johnson            1994   

      clase_medicamento          indicaciones      efectos_secundarios  \
580       Antipsychotic  Bacterial infections       Diarrhea, Headache   
792   Anti-inflammatory     Fungal infections  Dry mouth, Rash, Nausea   
1362     Antidepressant      Viral infections                 Headache   
1118        Antipyretic           Pain relief                 Headache   

      dosis_mg vía_administración contraindicaciones  \
580        150      Intramuscular           Diabetes   
792        350        Intravenous          Pregnancy   
1362       490             Rectal  Allergic reaction   
1118       880               Oral  Allergic reaction   

                     advertencias  precio_usd número_lote fecha_caducidad  \
580          May cause drowsiness        4.78     yk393yI      2027-03-13   
792        Monitor blood pressure      487.58     tS016hI      2028-05-11   
1362       Monitor blood pressure      208.51     aP252EZ      2026-05-28   
1118  Use with caution in elderly      408.46     jN868kk      2026-09-06   

     gravedad_efectos_secundarios estado_aprobación  
580                      Moderate           Pending  
792                          Mild          Approved  
1362                       Severe          Rejected  
1118                         Mild          Approved

In [606]:
# eliminar una columna

data = data.drop('Unnamed: 0', axis=1)

In [607]:
data.sample(4)

nombre_medicamento         fabricante  año_aprobación clase_medicamento  \
534        Rivaprofen18        Pfizer Inc.            2007        Antifungal   
1011       Fenocillin12   Roche Holding AG            2003     Antihistamine   
1125       Daxocillin76    GlaxoSmithKline            2000         Antiviral   
424        Loxoxetine44  Johnson & Johnson            2009           Vaccine   

                indicaciones  efectos_secundarios  dosis_mg  \
534     Bacterial infections            Dry mouth       230   
1011  Inflammation reduction  Dry mouth, Headache       680   
1125    Depression treatment              Fatigue       290   
424              Pain relief              Fatigue       280   

     vía_administración contraindicaciones                 advertencias  \
534       Intramuscular  Kidney impairment         May affect fertility   
1011         Inhalation             Asthma                Avoid alcohol   
1125            Topical           Seizures  Do not discontinue abruptly   
424          Sublingual           Seizures                Avoid alcohol   

      precio_usd número_lote fecha_caducidad gravedad_efectos_secundarios  \
534       474.81     cA260cr      2028-02-07                       Severe   
1011      196.27     PH156Lf      2026-06-06                         Mild   
1125      208.03     WN787Ys      2028-01-31                       Severe   
424       115.38     oL375JG      2027-11-16                       Severe   

     estado_aprobación  
534           Rejected  
1011          Rejected  
1125          Rejected  
424           Approved

In [608]:
data.dtypes

nombre_medicamento               object
fabricante                       object
año_aprobación                    int64
clase_medicamento                object
indicaciones                     object
efectos_secundarios              object
dosis_mg                          int64
vía_administración               object
contraindicaciones               object
advertencias                     object
precio_usd                      float64
número_lote                      object
fecha_caducidad                  object
gravedad_efectos_secundarios     object
estado_aprobación                object
dtype: object

In [609]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   nombre_medicamento            1436 non-null   object 
 1   fabricante                    1436 non-null   object 
 2   año_aprobación                1436 non-null   int64  
 3   clase_medicamento             1436 non-null   object 
 4   indicaciones                  1436 non-null   object 
 5   efectos_secundarios           1436 non-null   object 
 6   dosis_mg                      1436 non-null   int64  
 7   vía_administración            1436 non-null   object 
 8   contraindicaciones            1436 non-null   object 
 9   advertencias                  1436 non-null   object 
 10  precio_usd                    1436 non-null   float64
 11  número_lote                   1436 non-null   object 
 12  fecha_caducidad               1436 non-null   object 
 13  gra

In [610]:
data.isnull().sum()

nombre_medicamento              0
fabricante                      0
año_aprobación                  0
clase_medicamento               0
indicaciones                    0
efectos_secundarios             0
dosis_mg                        0
vía_administración              0
contraindicaciones              0
advertencias                    0
precio_usd                      0
número_lote                     0
fecha_caducidad                 0
gravedad_efectos_secundarios    0
estado_aprobación               0
dtype: int64

In [611]:
data.duplicated().sum()

np.int64(0)

In [612]:
data.describe()

año_aprobación     dosis_mg   precio_usd
count     1436.000000  1436.000000  1436.000000
mean      2006.860028   509.637883   251.844854
std         10.167067   286.417268   142.640781
min       1990.000000    10.000000     1.210000
25%       1998.000000   270.000000   128.830000
50%       2007.000000   515.000000   255.130000
75%       2016.000000   760.000000   372.207500
max       2024.000000   990.000000   499.060000

#  

---
# <center><Font Color="#615FFF" size="8"> Preparando Datos</Font> </center>
---

In [613]:
# biblioteca

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [614]:
# hecer copia profunda del dataframe
import copy
datos_ml = copy.deepcopy(data)

In [615]:
# eliminar columnas

datos_ml = datos_ml.drop(columns=['número_lote', 'fecha_caducidad'])

In [616]:
datos_ml.head(2)

nombre_medicamento   fabricante  año_aprobación clase_medicamento  \
0       Seroxetine50  AstraZeneca            1996    Antidepressant   
1        Mecoparin93  AstraZeneca            2018           Vaccine   

     indicaciones efectos_secundarios  dosis_mg vía_administración  \
0  Allergy relief     Fatigue, Nausea       260             Rectal   
1  Allergy relief              Nausea       470         Inhalation   

   contraindicaciones    advertencias  precio_usd  \
0  Bleeding disorders   Avoid alcohol      192.43   
1   Allergic reaction  Take with food      397.82   

  gravedad_efectos_secundarios estado_aprobación  
0                         Mild           Pending  
1                         Mild          Approved

In [617]:
# variables para machine

X = datos_ml.drop(columns=['estado_aprobación'])
y = datos_ml['estado_aprobación']

In [618]:
X = pd.get_dummies(X)

In [619]:
# dividir la prueba
X,X_test,y,y_test = train_test_split(X,y,test_size=0.15,stratify=y,random_state=42)
X_train,X_val,y_train,y_val = train_test_split(X,y,stratify=y,random_state=5)


In [620]:
modelo = RandomForestClassifier(
    random_state=42,
    max_depth=4,
    class_weight='balanced'
    )
modelo.fit(X_train, y_train)
print(f'La precisión del modelo train es de : {modelo.score(X_train, y_train) * 100:.2f}%')
print(f'La precisión del modelo de validación es de : {modelo.score(X_val, y_val) * 100:.2f}%')

La precisión del modelo train es de : 60.33%
La precisión del modelo de validación es de : 32.13%


In [621]:
y_pred = modelo.predict(X_test)

In [622]:
# Evaluación
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nReporte de Clasificación:\n", classification_report(y_test, y_pred))
print("\nMatriz de Confusión:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.3425925925925926

Reporte de Clasificación:
               precision    recall  f1-score   support

    Approved       0.30      0.30      0.30        69
     Pending       0.38      0.32      0.35        75
    Rejected       0.35      0.40      0.37        72

    accuracy                           0.34       216
   macro avg       0.34      0.34      0.34       216
weighted avg       0.34      0.34      0.34       216


Matriz de Confusión:
 [[21 19 29]
 [25 24 26]
 [23 20 29]]


In [623]:
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [624]:
# Aplicar SMOTE solo al entrenamiento
smote = SMOTE(random_state=42)
X_train_bal, y_train_bal = smote.fit_resample(X_train, y_train)

print("Distribución original de clases en train:")
print(y_train.value_counts())
print("\nDistribución balanceada de clases en train:")
print(pd.Series(y_train_bal).value_counts())

Distribución original de clases en train:
estado_aprobación
Pending     316
Rejected    304
Approved    295
Name: count, dtype: int64

Distribución balanceada de clases en train:
estado_aprobación
Rejected    316
Approved    316
Pending     316
Name: count, dtype: int64


In [625]:
# Modelo con los mejores parámetros encontrados
modelo_smote = RandomForestClassifier(
    random_state=42,
    max_depth=6,
    n_estimators=200,
    min_samples_split=2
)

In [626]:
# Entrenar
modelo_smote.fit(X_train_bal, y_train_bal)

RandomForestClassifier(max_depth=6, n_estimators=200, random_state=42)

In [627]:
# Validación
y_val_pred = modelo_smote.predict(X_val)
print(f'\nPrecisión en validación: {accuracy_score(y_val, y_val_pred) * 100:.2f}%')
print("\nReporte de Clasificación (Validación):")
print(classification_report(y_val, y_val_pred))
print("Matriz de Confusión (Validación):")
print(confusion_matrix(y_val, y_val_pred))


Precisión en validación: 29.18%

Reporte de Clasificación (Validación):
              precision    recall  f1-score   support

    Approved       0.30      0.30      0.30        98
     Pending       0.28      0.29      0.28       105
    Rejected       0.29      0.29      0.29       102

    accuracy                           0.29       305
   macro avg       0.29      0.29      0.29       305
weighted avg       0.29      0.29      0.29       305

Matriz de Confusión (Validación):
[[29 37 32]
 [35 30 40]
 [33 39 30]]


In [628]:
# Test final
y_test_pred = modelo_smote.predict(X_test)
print(f'\nAccuracy en test: {accuracy_score(y_test, y_test_pred) * 100:.2f}%')
print("\nReporte de Clasificación (Test):")
print(classification_report(y_test, y_test_pred))
print("Matriz de Confusión (Test):")
print(confusion_matrix(y_test, y_test_pred))


Accuracy en test: 31.94%

Reporte de Clasificación (Test):
              precision    recall  f1-score   support

    Approved       0.27      0.23      0.25        69
     Pending       0.35      0.35      0.35        75
    Rejected       0.33      0.38      0.35        72

    accuracy                           0.32       216
   macro avg       0.32      0.32      0.32       216
weighted avg       0.32      0.32      0.32       216

Matriz de Confusión (Test):
[[16 25 28]
 [23 26 26]
 [21 24 27]]
