<a href="https://colab.research.google.com/github/r2x4/aprendiendo_machine/blob/main/machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  

----
# <center><font color="#615FFF" size="8"> Practice Machine Learning </font></center>
----

In [328]:
# llamar datos
import pandas as pd

datos = pd.read_csv('/content/realistic_drug_labels_side_effects.csv')

In [329]:
datos.shape

(1436, 15)

In [330]:
datos.sample(4)

drug_name      manufacturer  approval_year   drug_class  \
675      Rivavir33  Roche Holding AG           2017      Vaccine   
299   Fenoxetine54  Roche Holding AG           2023   Antifungal   
66       Serovir30   GlaxoSmithKline           2011  Antipyretic   
1148   Rivazepam43            Sanofi           2020  Antipyretic   

                 indications                  side_effects  dosage_mg  \
675   Inflammation reduction                       Fatigue        490   
299        Fungal infections   Dizziness, Nausea, Insomnia        760   
66      Bacterial infections  Nausea, Rash, Blurred vision        350   
1148  Inflammation reduction                       Fatigue        810   

     administration_route    contraindications                     warnings  \
675            Inhalation  High blood pressure  Use with caution in elderly   
299            Sublingual            Pregnancy         May affect fertility   
66                Topical        Liver disease         May cause drowsiness   
1148               Rectal  High blood pressure         May affect fertility   

      price_usd batch_number expiry_date side_effect_severity approval_status  
675      163.61      nm994jQ  2026-05-14             Moderate        Rejected  
299      302.56      ES016Ze  2027-09-16               Severe         Pending  
66       310.21      Fw257WN  2027-02-01               Severe         Pending  
1148      58.56      kx788PY  2026-01-27               Severe         Pending

In [331]:
datos.columns

Index(['drug_name', 'manufacturer', 'approval_year', 'drug_class',
       'indications', 'side_effects', 'dosage_mg', 'administration_route',
       'contraindications', 'warnings', 'price_usd', 'batch_number',
       'expiry_date', 'side_effect_severity', 'approval_status'],
      dtype='object')

In [332]:
# renombrar la columnas

datos.columns = [
    "nombre_medicamento",
    "fabricante",
    "año_aprobación",
    "clase_medicamento",
    "indicaciones",
    "efectos_secundarios",
    "dosis_mg",
    "vía_administración",
    "contraindicaciones",
    "advertencias",
    "precio_usd",
    "número_lote",
    "fecha_caducidad",
    "gravedad_efectos_secundarios",
    "estado_aprobación"
]

In [333]:
datos.sample(4)

nombre_medicamento            fabricante  año_aprobación  \
57         Seroxetine12           Merck & Co.            2008   
222        Serostatin53           Merck & Co.            2018   
822           Zylovir52  Moderna Therapeutics            1995   
1120         Mecozole80     Johnson & Johnson            1993   

      clase_medicamento            indicaciones  efectos_secundarios  \
57    Anti-inflammatory    Bacterial infections     Insomnia, Nausea   
222       Antipsychotic       Fungal infections  Dry mouth, Insomnia   
822           Antiviral         Fever reduction    Insomnia, Fatigue   
1120  Anti-inflammatory  Inflammation reduction     Insomnia, Nausea   

      dosis_mg vía_administración  contraindicaciones  \
57         370            Topical  Bleeding disorders   
222        620               Oral       Heart disease   
822        750      Intramuscular       Heart disease   
1120       830         Sublingual   Kidney impairment   

                     advertencias  precio_usd número_lote fecha_caducidad  \
57           May affect fertility      283.08     jN802tQ      2025-12-30   
222      Do not operate machinery      125.29     Be742ul      2026-07-28   
822             Risk of addiction      438.19     QE001XH      2025-12-10   
1120  Do not discontinue abruptly      471.58     cO782hU      2025-08-21   

     gravedad_efectos_secundarios estado_aprobación  
57                       Moderate          Rejected  
222                        Severe          Approved  
822                          Mild          Approved  
1120                     Moderate          Rejected

In [334]:
# exportar a csv

datos.to_csv('datos.csv')

In [335]:
# llamar la nueva base

data = pd.read_csv('/content/datos.csv')

In [336]:
data.sample(4)

Unnamed: 0 nombre_medicamento         fabricante  año_aprobación  \
26            26          Loxomab59  Johnson & Johnson            1990   
568          568       Rivaprofen59    GlaxoSmithKline            2013   
1130        1130        Cefdipine66    GlaxoSmithKline            2011   
158          158        Cefcillin20   Roche Holding AG            2016   

      clase_medicamento                indicaciones  \
26        Antipsychotic        Bacterial infections   
568             Vaccine              Allergy relief   
1130  Anti-inflammatory        Depression treatment   
158          Antibiotic  Prevent infectious disease   

                      efectos_secundarios  dosis_mg vía_administración  \
26                              Dry mouth        10               Oral   
568                             Dizziness       770             Rectal   
1130                     Nausea, Diarrhea        70         Inhalation   
158   Diarrhea, Blurred vision, Dry mouth       500        Intravenous   

      contraindicaciones            advertencias  precio_usd número_lote  \
26         Heart disease    May affect fertility      146.95     dU359vk   
568   Bleeding disorders       Risk of addiction      285.73     HB586gZ   
1130           Pregnancy    May cause drowsiness      140.58     Uf970RC   
158        Liver disease  Monitor blood pressure      293.08     zu167hg   

     fecha_caducidad gravedad_efectos_secundarios estado_aprobación  
26        2026-02-18                       Severe           Pending  
568       2028-02-11                       Severe           Pending  
1130      2026-11-30                       Severe           Pending  
158       2027-09-13                         Mild          Approved

In [337]:
# eliminar una columna

data = data.drop('Unnamed: 0', axis=1)

In [338]:
data.sample(4)

nombre_medicamento         fabricante  año_aprobación  clase_medicamento  \
716        Rivaparin62    GlaxoSmithKline            2013          Antiviral   
619         Cefzepam49  Johnson & Johnson            2005  Anti-inflammatory   
104        Loxoparin23        Merck & Co.            2020         Antibiotic   
933       Virastatin79        Novartis AG            2023  Anti-inflammatory   

             indicaciones                   efectos_secundarios  dosis_mg  \
716     Psychosis control                  Constipation, Nausea       600   
619  Depression treatment                    Headache, Insomnia        80   
104        Allergy relief  Dizziness, Blurred vision, Dry mouth       740   
933     Psychosis control       Dry mouth, Blurred vision, Rash       980   

    vía_administración contraindicaciones             advertencias  \
716      Intramuscular      Heart disease  Avoid sunlight exposure   
619         Inhalation          Pregnancy        Risk of addiction   
104            Topical  Allergic reaction     May affect fertility   
933         Sublingual      Liver disease            Avoid alcohol   

     precio_usd número_lote fecha_caducidad gravedad_efectos_secundarios  \
716       69.00     Px897Gm      2026-02-09                       Severe   
619      434.45     kq560RS      2026-12-22                       Severe   
104       71.52     zW928gc      2025-12-11                     Moderate   
933        5.01     sU526TW      2027-05-11                     Moderate   

    estado_aprobación  
716          Approved  
619          Approved  
104           Pending  
933          Approved

In [339]:
data.dtypes

nombre_medicamento               object
fabricante                       object
año_aprobación                    int64
clase_medicamento                object
indicaciones                     object
efectos_secundarios              object
dosis_mg                          int64
vía_administración               object
contraindicaciones               object
advertencias                     object
precio_usd                      float64
número_lote                      object
fecha_caducidad                  object
gravedad_efectos_secundarios     object
estado_aprobación                object
dtype: object

In [340]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   nombre_medicamento            1436 non-null   object 
 1   fabricante                    1436 non-null   object 
 2   año_aprobación                1436 non-null   int64  
 3   clase_medicamento             1436 non-null   object 
 4   indicaciones                  1436 non-null   object 
 5   efectos_secundarios           1436 non-null   object 
 6   dosis_mg                      1436 non-null   int64  
 7   vía_administración            1436 non-null   object 
 8   contraindicaciones            1436 non-null   object 
 9   advertencias                  1436 non-null   object 
 10  precio_usd                    1436 non-null   float64
 11  número_lote                   1436 non-null   object 
 12  fecha_caducidad               1436 non-null   object 
 13  gra

In [341]:
data.isnull().sum()

nombre_medicamento              0
fabricante                      0
año_aprobación                  0
clase_medicamento               0
indicaciones                    0
efectos_secundarios             0
dosis_mg                        0
vía_administración              0
contraindicaciones              0
advertencias                    0
precio_usd                      0
número_lote                     0
fecha_caducidad                 0
gravedad_efectos_secundarios    0
estado_aprobación               0
dtype: int64

In [342]:
data.duplicated().sum()

np.int64(0)

In [343]:
data.describe()

año_aprobación     dosis_mg   precio_usd
count     1436.000000  1436.000000  1436.000000
mean      2006.860028   509.637883   251.844854
std         10.167067   286.417268   142.640781
min       1990.000000    10.000000     1.210000
25%       1998.000000   270.000000   128.830000
50%       2007.000000   515.000000   255.130000
75%       2016.000000   760.000000   372.207500
max       2024.000000   990.000000   499.060000

#  

---
# <center><Font Color="#615FFF" size="8"> Preparando Datos</Font> </center>
---

In [344]:
# biblioteca

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [345]:
# hecer copia profunda del dataframe
import copy
datos_ml = copy.deepcopy(data)

In [346]:
# eliminar columnas

datos_ml = datos_ml.drop(columns=['número_lote', 'fecha_caducidad'])

In [347]:
datos_ml.head(2)

nombre_medicamento   fabricante  año_aprobación clase_medicamento  \
0       Seroxetine50  AstraZeneca            1996    Antidepressant   
1        Mecoparin93  AstraZeneca            2018           Vaccine   

     indicaciones efectos_secundarios  dosis_mg vía_administración  \
0  Allergy relief     Fatigue, Nausea       260             Rectal   
1  Allergy relief              Nausea       470         Inhalation   

   contraindicaciones    advertencias  precio_usd  \
0  Bleeding disorders   Avoid alcohol      192.43   
1   Allergic reaction  Take with food      397.82   

  gravedad_efectos_secundarios estado_aprobación  
0                         Mild           Pending  
1                         Mild          Approved

In [348]:
# variables para machine

X = datos_ml.drop(columns=['estado_aprobación'])
y = datos_ml['estado_aprobación']

In [349]:
X = pd.get_dummies(X)

In [350]:
# dividir la prueba
X,X_test,y,y_test = train_test_split(X,y,test_size=0.15,stratify=y,random_state=42)
X_train,X_val,y_train,y_val = train_test_split(X,y,stratify=y,random_state=5)


In [351]:
modelo = RandomForestClassifier(
    random_state=42,
    max_depth=4,
    class_weight='balanced'
    )
modelo.fit(X_train, y_train)
print(f'La precisión del modelo train es de : {modelo.score(X_train, y_train) * 100:.2f}%')
print(f'La precisión del modelo de validación es de : {modelo.score(X_val, y_val) * 100:.2f}%')

La precisión del modelo train es de : 60.33%
La precisión del modelo de validación es de : 32.13%


In [352]:
y_pred = modelo.predict(X_test)

In [353]:
# Evaluación
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nReporte de Clasificación:\n", classification_report(y_test, y_pred))
print("\nMatriz de Confusión:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.3425925925925926

Reporte de Clasificación:
               precision    recall  f1-score   support

    Approved       0.30      0.30      0.30        69
     Pending       0.38      0.32      0.35        75
    Rejected       0.35      0.40      0.37        72

    accuracy                           0.34       216
   macro avg       0.34      0.34      0.34       216
weighted avg       0.34      0.34      0.34       216


Matriz de Confusión:
 [[21 19 29]
 [25 24 26]
 [23 20 29]]


In [354]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

In [355]:
# Definir parámetros
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 4, 5, 6, 8, None],
    'min_samples_split': [2, 5, 10]
}

In [356]:
# Modelo base con balanceo
rf = RandomForestClassifier(random_state=42, class_weight='balanced')

# GridSearch
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,  # validación cruzada de 5 folds
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

In [ ]:

# Entrenar búsqueda
grid_search.fit(X_train, y_train)

# Mostrar mejor combinación
print("Mejores hiperparámetros:", grid_search.best_params_)
print("Mejor score de validación:", grid_search.best_score_)

# Evaluar en test
mejor_modelo = grid_search.best_estimator_
y_pred = mejor_modelo.predict(X_test)

print("\nAccuracy en test:", accuracy_score(y_test, y_pred))
print("\nReporte de Clasificación:\n", classification_report(y_test, y_pred))
print("\nMatriz de Confusión:\n", confusion_matrix(y_test, y_pred))


Fitting 5 folds for each of 54 candidates, totalling 270 fits
