<a href="https://colab.research.google.com/github/r2x4/aprendiendo_machine/blob/main/machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  

----
# <center><font color="#615FFF" size="8"> Practice Machine Learning </font></center>
----

In [392]:
# llamar datos
import pandas as pd

datos = pd.read_csv('/content/realistic_drug_labels_side_effects.csv')

In [393]:
datos.shape

(1436, 15)

In [394]:
datos.sample(4)

drug_name manufacturer  approval_year         drug_class  \
748    Cefstatin33  Novartis AG           2010  Anti-inflammatory   
1095  Viraprofen98  AstraZeneca           1992      Antipsychotic   
875    Cefprofen68  Novartis AG           1998        Antipyretic   
400   Viraprofen25  Merck & Co.           2014         Antifungal   

               indications                side_effects  dosage_mg  \
748            Pain relief                    Diarrhea        720   
1095      Viral infections  Insomnia, Nausea, Headache        220   
875            Pain relief       Constipation, Fatigue        640   
400   Bacterial infections       Constipation, Fatigue        270   

     administration_route   contraindications                     warnings  \
748            Sublingual            Seizures         May cause drowsiness   
1095           Inhalation              Asthma  Use with caution in elderly   
875         Intramuscular  Bleeding disorders         May affect fertility   
400            Sublingual   Allergic reaction  Use with caution in elderly   

      price_usd batch_number expiry_date side_effect_severity approval_status  
748      436.12      Ab237WJ  2026-10-06             Moderate        Rejected  
1095     430.68      BE811qy  2026-03-12               Severe         Pending  
875      187.06      WJ649ZW  2026-06-29               Severe         Pending  
400      196.65      ZO544XT  2025-12-10                 Mild        Rejected

In [395]:
datos.columns

Index(['drug_name', 'manufacturer', 'approval_year', 'drug_class',
       'indications', 'side_effects', 'dosage_mg', 'administration_route',
       'contraindications', 'warnings', 'price_usd', 'batch_number',
       'expiry_date', 'side_effect_severity', 'approval_status'],
      dtype='object')

In [396]:
# renombrar la columnas

datos.columns = [
    "nombre_medicamento",
    "fabricante",
    "año_aprobación",
    "clase_medicamento",
    "indicaciones",
    "efectos_secundarios",
    "dosis_mg",
    "vía_administración",
    "contraindicaciones",
    "advertencias",
    "precio_usd",
    "número_lote",
    "fecha_caducidad",
    "gravedad_efectos_secundarios",
    "estado_aprobación"
]

In [397]:
datos.sample(4)

nombre_medicamento            fabricante  año_aprobación  \
164        Loxocillin65           AstraZeneca            2014   
1087         Serozole18  Moderna Therapeutics            1999   
1389        Cefxetine26                Sanofi            2019   
401        Viracillin43                Sanofi            2011   

     clase_medicamento            indicaciones efectos_secundarios  dosis_mg  \
164            Vaccine             Pain relief           Dizziness       270   
1087        Antifungal  Inflammation reduction           Dry mouth       680   
1389    Antidepressant         Fever reduction            Headache       130   
401          Analgesic         Fever reduction      Blurred vision       330   

     vía_administración   contraindicaciones                 advertencias  \
164              Rectal    Allergic reaction               Take with food   
1087        Intravenous  High blood pressure            Risk of addiction   
1389      Intramuscular               Asthma  Do not discontinue abruptly   
401                Oral    Allergic reaction               Take with food   

      precio_usd número_lote fecha_caducidad gravedad_efectos_secundarios  \
164       242.68     QA464LE      2028-07-24                         Mild   
1087       99.84     hT289Dr      2027-04-02                         Mild   
1389       97.42     Bg745RA      2027-12-04                         Mild   
401       151.65     vm355Ei      2026-09-08                         Mild   

     estado_aprobación  
164           Approved  
1087          Approved  
1389          Rejected  
401            Pending

In [398]:
# exportar a csv

datos.to_csv('datos.csv')

In [399]:
# llamar la nueva base

data = pd.read_csv('/content/datos.csv')

In [400]:
data.sample(4)

Unnamed: 0 nombre_medicamento         fabricante  año_aprobación  \
168          168          Rivavir82        AstraZeneca            2017   
1019        1019          Amoxvir11  Johnson & Johnson            2000   
1434        1434       Mecoprofen32    GlaxoSmithKline            1994   
263          263       Zyloprofen49  Johnson & Johnson            2004   

     clase_medicamento                indicaciones  \
168         Antibiotic        Bacterial infections   
1019         Analgesic  Prevent infectious disease   
1434        Antifungal        Bacterial infections   
263     Antidepressant      Inflammation reduction   

                    efectos_secundarios  dosis_mg vía_administración  \
168             Fatigue, Rash, Diarrhea       990             Rectal   
1019  Dry mouth, Constipation, Headache       300      Intramuscular   
1434                           Headache       670            Topical   
263                   Fatigue, Insomnia       970         Inhalation   

     contraindicaciones             advertencias  precio_usd número_lote  \
168           Pregnancy   Monitor blood pressure      381.56     Hy005fr   
1019  Allergic reaction  Avoid sunlight exposure      357.40     gQ115Gk   
1434             Asthma     May cause drowsiness      263.19     qM405ML   
263   Kidney impairment           Take with food      315.28     lT936wf   

     fecha_caducidad gravedad_efectos_secundarios estado_aprobación  
168       2028-04-11                     Moderate          Approved  
1019      2027-05-15                     Moderate           Pending  
1434      2028-05-13                       Severe           Pending  
263       2027-02-16                         Mild          Approved

In [401]:
# eliminar una columna

data = data.drop('Unnamed: 0', axis=1)

In [402]:
data.sample(4)

nombre_medicamento        fabricante  año_aprobación clase_medicamento  \
992          Fenozole66       Merck & Co.            1997       Antipyretic   
1028        Fenoparin68       Pfizer Inc.            2003        Antifungal   
723        Zyloprofen42  Roche Holding AG            2003     Antipsychotic   
1240        Daxozepam62            Sanofi            2001     Antihistamine   

                indicaciones                 efectos_secundarios  dosis_mg  \
992   Inflammation reduction  Blurred vision, Insomnia, Headache       650   
1028        Viral infections                      Blurred vision       850   
723     Bacterial infections              Headache, Constipation       600   
1240             Pain relief         Nausea, Dry mouth, Insomnia       970   

     vía_administración  contraindicaciones          advertencias  precio_usd  \
992         Intravenous       Heart disease        Take with food      421.60   
1028         Inhalation  Bleeding disorders  May cause drowsiness      336.24   
723             Topical           Pregnancy         Avoid alcohol      166.37   
1240               Oral   Kidney impairment         Avoid alcohol       85.92   

     número_lote fecha_caducidad gravedad_efectos_secundarios  \
992      IA182eS      2027-10-10                         Mild   
1028     rX122FU      2028-03-10                         Mild   
723      QW630JT      2026-10-03                         Mild   
1240     yH010kM      2028-01-24                         Mild   

     estado_aprobación  
992           Rejected  
1028          Approved  
723           Approved  
1240          Approved

In [403]:
data.dtypes

nombre_medicamento               object
fabricante                       object
año_aprobación                    int64
clase_medicamento                object
indicaciones                     object
efectos_secundarios              object
dosis_mg                          int64
vía_administración               object
contraindicaciones               object
advertencias                     object
precio_usd                      float64
número_lote                      object
fecha_caducidad                  object
gravedad_efectos_secundarios     object
estado_aprobación                object
dtype: object

In [404]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   nombre_medicamento            1436 non-null   object 
 1   fabricante                    1436 non-null   object 
 2   año_aprobación                1436 non-null   int64  
 3   clase_medicamento             1436 non-null   object 
 4   indicaciones                  1436 non-null   object 
 5   efectos_secundarios           1436 non-null   object 
 6   dosis_mg                      1436 non-null   int64  
 7   vía_administración            1436 non-null   object 
 8   contraindicaciones            1436 non-null   object 
 9   advertencias                  1436 non-null   object 
 10  precio_usd                    1436 non-null   float64
 11  número_lote                   1436 non-null   object 
 12  fecha_caducidad               1436 non-null   object 
 13  gra

In [405]:
data.isnull().sum()

nombre_medicamento              0
fabricante                      0
año_aprobación                  0
clase_medicamento               0
indicaciones                    0
efectos_secundarios             0
dosis_mg                        0
vía_administración              0
contraindicaciones              0
advertencias                    0
precio_usd                      0
número_lote                     0
fecha_caducidad                 0
gravedad_efectos_secundarios    0
estado_aprobación               0
dtype: int64

In [406]:
data.duplicated().sum()

np.int64(0)

In [407]:
data.describe()

año_aprobación     dosis_mg   precio_usd
count     1436.000000  1436.000000  1436.000000
mean      2006.860028   509.637883   251.844854
std         10.167067   286.417268   142.640781
min       1990.000000    10.000000     1.210000
25%       1998.000000   270.000000   128.830000
50%       2007.000000   515.000000   255.130000
75%       2016.000000   760.000000   372.207500
max       2024.000000   990.000000   499.060000

#  

---
# <center><Font Color="#615FFF" size="8"> Preparando Datos</Font> </center>
---

In [408]:
# biblioteca

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [409]:
# hecer copia profunda del dataframe
import copy
datos_ml = copy.deepcopy(data)

In [410]:
# eliminar columnas

datos_ml = datos_ml.drop(columns=['número_lote', 'fecha_caducidad'])

In [411]:
datos_ml.head(2)

nombre_medicamento   fabricante  año_aprobación clase_medicamento  \
0       Seroxetine50  AstraZeneca            1996    Antidepressant   
1        Mecoparin93  AstraZeneca            2018           Vaccine   

     indicaciones efectos_secundarios  dosis_mg vía_administración  \
0  Allergy relief     Fatigue, Nausea       260             Rectal   
1  Allergy relief              Nausea       470         Inhalation   

   contraindicaciones    advertencias  precio_usd  \
0  Bleeding disorders   Avoid alcohol      192.43   
1   Allergic reaction  Take with food      397.82   

  gravedad_efectos_secundarios estado_aprobación  
0                         Mild           Pending  
1                         Mild          Approved

In [412]:
# variables para machine

X = datos_ml.drop(columns=['estado_aprobación'])
y = datos_ml['estado_aprobación']

In [413]:
X = pd.get_dummies(X)

In [414]:
# dividir la prueba
X,X_test,y,y_test = train_test_split(X,y,test_size=0.15,stratify=y,random_state=42)
X_train,X_val,y_train,y_val = train_test_split(X,y,stratify=y,random_state=5)


In [415]:
modelo = RandomForestClassifier(
    random_state=42,
    max_depth=4,
    class_weight='balanced'
    )
modelo.fit(X_train, y_train)
print(f'La precisión del modelo train es de : {modelo.score(X_train, y_train) * 100:.2f}%')
print(f'La precisión del modelo de validación es de : {modelo.score(X_val, y_val) * 100:.2f}%')

La precisión del modelo train es de : 60.33%
La precisión del modelo de validación es de : 32.13%


In [416]:
y_pred = modelo.predict(X_test)

In [417]:
# Evaluación
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nReporte de Clasificación:\n", classification_report(y_test, y_pred))
print("\nMatriz de Confusión:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.3425925925925926

Reporte de Clasificación:
               precision    recall  f1-score   support

    Approved       0.30      0.30      0.30        69
     Pending       0.38      0.32      0.35        75
    Rejected       0.35      0.40      0.37        72

    accuracy                           0.34       216
   macro avg       0.34      0.34      0.34       216
weighted avg       0.34      0.34      0.34       216


Matriz de Confusión:
 [[21 19 29]
 [25 24 26]
 [23 20 29]]


In [418]:
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [419]:
# Aplicar SMOTE solo al entrenamiento
smote = SMOTE(random_state=42)
X_train_bal, y_train_bal = smote.fit_resample(X_train, y_train)

print("Distribución original de clases en train:")
print(y_train.value_counts())
print("\nDistribución balanceada de clases en train:")
print(pd.Series(y_train_bal).value_counts())

Distribución original de clases en train:
estado_aprobación
Pending     316
Rejected    304
Approved    295
Name: count, dtype: int64

Distribución balanceada de clases en train:
estado_aprobación
Rejected    316
Approved    316
Pending     316
Name: count, dtype: int64


In [420]:
# Modelo con los mejores parámetros encontrados
modelo_smote = RandomForestClassifier(
    random_state=42,
    max_depth=6,
    n_estimators=200,
    min_samples_split=2
)

In [421]:
# Entrenar
modelo_smote.fit(X_train_bal, y_train_bal)

RandomForestClassifier(max_depth=6, n_estimators=200, random_state=42)

In [422]:
# Validación
y_val_pred = modelo_smote.predict(X_val)
print(f'\nPrecisión en validación: {accuracy_score(y_val, y_val_pred) * 100:.2f}%')
print("\nReporte de Clasificación (Validación):")
print(classification_report(y_val, y_val_pred))
print("Matriz de Confusión (Validación):")
print(confusion_matrix(y_val, y_val_pred))


Precisión en validación: 29.18%

Reporte de Clasificación (Validación):
              precision    recall  f1-score   support

    Approved       0.30      0.30      0.30        98
     Pending       0.28      0.29      0.28       105
    Rejected       0.29      0.29      0.29       102

    accuracy                           0.29       305
   macro avg       0.29      0.29      0.29       305
weighted avg       0.29      0.29      0.29       305

Matriz de Confusión (Validación):
[[29 37 32]
 [35 30 40]
 [33 39 30]]


In [423]:
# Test final
y_test_pred = modelo_smote.predict(X_test)
print(f'\nAccuracy en test: {accuracy_score(y_test, y_test_pred) * 100:.2f}%')
print("\nReporte de Clasificación (Test):")
print(classification_report(y_test, y_test_pred))
print("Matriz de Confusión (Test):")
print(confusion_matrix(y_test, y_test_pred))


Accuracy en test: 31.94%

Reporte de Clasificación (Test):
              precision    recall  f1-score   support

    Approved       0.27      0.23      0.25        69
     Pending       0.35      0.35      0.35        75
    Rejected       0.33      0.38      0.35        72

    accuracy                           0.32       216
   macro avg       0.32      0.32      0.32       216
weighted avg       0.32      0.32      0.32       216

Matriz de Confusión (Test):
[[16 25 28]
 [23 26 26]
 [21 24 27]]
