<a href="https://colab.research.google.com/github/r2x4/aprendiendo_machine/blob/main/machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  

----
# <center><font color="#615FFF" size="8"> Practice Machine Learning </font></center>
----

In [92]:
# llamar datos
import pandas as pd

datos = pd.read_csv('/content/realistic_drug_labels_side_effects.csv')

In [93]:
datos.shape

(1436, 15)

In [94]:
datos.sample(4)

drug_name       manufacturer  approval_year     drug_class  \
605   Serodipine33        AstraZeneca           2017     Antifungal   
26       Loxomab59  Johnson & Johnson           1990  Antipsychotic   
1312     Mecomab15        Novartis AG           2021     Antibiotic   
18     Mecoparin65             Sanofi           2016      Antiviral   

               indications          side_effects  dosage_mg  \
605        Fever reduction       Nausea, Fatigue        150   
26    Bacterial infections             Dry mouth         10   
1312     Psychosis control  Dry mouth, Dizziness        860   
18    Bacterial infections     Fatigue, Diarrhea        990   

     administration_route   contraindications                     warnings  \
605           Intravenous  Bleeding disorders       Monitor blood pressure   
26                   Oral       Heart disease         May affect fertility   
1312               Rectal   Allergic reaction  Do not discontinue abruptly   
18            Intravenous              Asthma  Use with caution in elderly   

      price_usd batch_number expiry_date side_effect_severity approval_status  
605      127.45      pZ499Xz  2026-12-31             Moderate         Pending  
26       146.95      dU359vk  2026-02-18               Severe         Pending  
1312     230.60      ow267wD  2027-08-07               Severe        Rejected  
18       270.85      xl072nC  2027-12-03                 Mild         Pending

In [95]:
datos.columns

Index(['drug_name', 'manufacturer', 'approval_year', 'drug_class',
       'indications', 'side_effects', 'dosage_mg', 'administration_route',
       'contraindications', 'warnings', 'price_usd', 'batch_number',
       'expiry_date', 'side_effect_severity', 'approval_status'],
      dtype='object')

In [96]:
# renombrar la columnas

datos.columns = [
    "nombre_medicamento",
    "fabricante",
    "año_aprobación",
    "clase_medicamento",
    "indicaciones",
    "efectos_secundarios",
    "dosis_mg",
    "vía_administración",
    "contraindicaciones",
    "advertencias",
    "precio_usd",
    "número_lote",
    "fecha_caducidad",
    "gravedad_efectos_secundarios",
    "estado_aprobación"
]

In [97]:
datos.sample(4)

nombre_medicamento            fabricante  año_aprobación  \
1085       Zylodipine64  Moderna Therapeutics            2003   
148         Daxoparin72      Roche Holding AG            1995   
447        Loxoxetine13           Pfizer Inc.            1991   
78            Zylovir64       GlaxoSmithKline            2008   

     clase_medicamento                indicaciones  \
1085           Vaccine  Prevent infectious disease   
148        Antipyretic        Bacterial infections   
447          Analgesic              Allergy relief   
78           Antiviral        Bacterial infections   

                     efectos_secundarios  dosis_mg vía_administración  \
1085                  Fatigue, Dry mouth        40      Intramuscular   
148                         Constipation       520            Topical   
447    Nausea, Dry mouth, Blurred vision       810         Sublingual   
78    Dry mouth, Fatigue, Blurred vision        20            Topical   

      contraindicaciones                 advertencias  precio_usd número_lote  \
1085       Heart disease      Avoid sunlight exposure      112.94     Xz585tl   
148               Asthma  Do not discontinue abruptly      280.68     VS250ia   
447   Bleeding disorders       Monitor blood pressure      455.06     Lc906Fw   
78             Pregnancy            Risk of addiction      333.46     RR246xi   

     fecha_caducidad gravedad_efectos_secundarios estado_aprobación  
1085      2028-07-01                       Severe          Rejected  
148       2027-02-06                     Moderate          Approved  
447       2026-03-17                       Severe          Rejected  
78        2027-07-21                         Mild          Rejected

In [98]:
# exportar a csv

datos.to_csv('datos.csv')

In [99]:
# llamar la nueva base

data = pd.read_csv('/content/datos.csv')

In [100]:
data.sample(4)

Unnamed: 0 nombre_medicamento   fabricante  año_aprobación  \
273          273         Fenozole34  Pfizer Inc.            2021   
400          400       Viraprofen25  Merck & Co.            2014   
1061        1061       Daxodipine57  Novartis AG            2008   
1297        1297        Cefstatin50  Merck & Co.            2014   

      clase_medicamento          indicaciones     efectos_secundarios  \
273   Anti-inflammatory  Bacterial infections  Nausea, Blurred vision   
400          Antifungal  Bacterial infections   Constipation, Fatigue   
1061      Antipsychotic  Bacterial infections       Diarrhea, Fatigue   
1297         Antifungal     Psychosis control      Fatigue, Dizziness   

      dosis_mg vía_administración contraindicaciones  \
273        920               Oral  Kidney impairment   
400        270         Sublingual  Allergic reaction   
1061       360        Intravenous           Seizures   
1297       230             Rectal             Asthma   

                     advertencias  precio_usd número_lote fecha_caducidad  \
273       Avoid sunlight exposure      425.12     lg016Mo      2025-08-27   
400   Use with caution in elderly      196.65     ZO544XT      2025-12-10   
1061  Use with caution in elderly       95.93     GU349SK      2027-10-30   
1297       Monitor blood pressure      221.68     ff676uI      2028-03-04   

     gravedad_efectos_secundarios estado_aprobación  
273                          Mild          Approved  
400                          Mild          Rejected  
1061                       Severe           Pending  
1297                     Moderate           Pending

In [101]:
# eliminar una columna

data = data.drop('Unnamed: 0', axis=1)

In [102]:
data.sample(4)

nombre_medicamento            fabricante  año_aprobación  \
785       Serodipine59                Sanofi            2001   
86        Amoxdipine25              Bayer AG            2010   
700       Seroxetine67       GlaxoSmithKline            2017   
916          Amoxmab24  Moderna Therapeutics            2014   

    clase_medicamento                indicaciones  \
785    Antidepressant           Psychosis control   
86         Antifungal  Prevent infectious disease   
700       Antipyretic  Prevent infectious disease   
916     Antipsychotic      Inflammation reduction   

                efectos_secundarios  dosis_mg vía_administración  \
785        Blurred vision, Insomnia       220         Inhalation   
86             Dry mouth, Dizziness       930        Intravenous   
700  Dizziness, Dry mouth, Diarrhea       580         Inhalation   
916       Insomnia, Dry mouth, Rash       310        Intravenous   

      contraindicaciones                 advertencias  precio_usd número_lote  \
785  High blood pressure  Do not discontinue abruptly      256.59     Eq510dI   
86     Allergic reaction  Use with caution in elderly       31.58     hN266RU   
700        Heart disease  Use with caution in elderly       58.09     NP073Aj   
916               Asthma  Do not discontinue abruptly      127.93     Sd286DX   

    fecha_caducidad gravedad_efectos_secundarios estado_aprobación  
785      2026-11-18                       Severe          Approved  
86       2027-08-03                     Moderate          Rejected  
700      2027-09-01                       Severe          Approved  
916      2026-06-15                     Moderate          Rejected

In [103]:
data.dtypes

nombre_medicamento               object
fabricante                       object
año_aprobación                    int64
clase_medicamento                object
indicaciones                     object
efectos_secundarios              object
dosis_mg                          int64
vía_administración               object
contraindicaciones               object
advertencias                     object
precio_usd                      float64
número_lote                      object
fecha_caducidad                  object
gravedad_efectos_secundarios     object
estado_aprobación                object
dtype: object

In [104]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   nombre_medicamento            1436 non-null   object 
 1   fabricante                    1436 non-null   object 
 2   año_aprobación                1436 non-null   int64  
 3   clase_medicamento             1436 non-null   object 
 4   indicaciones                  1436 non-null   object 
 5   efectos_secundarios           1436 non-null   object 
 6   dosis_mg                      1436 non-null   int64  
 7   vía_administración            1436 non-null   object 
 8   contraindicaciones            1436 non-null   object 
 9   advertencias                  1436 non-null   object 
 10  precio_usd                    1436 non-null   float64
 11  número_lote                   1436 non-null   object 
 12  fecha_caducidad               1436 non-null   object 
 13  gra

In [105]:
data.isnull().sum()

nombre_medicamento              0
fabricante                      0
año_aprobación                  0
clase_medicamento               0
indicaciones                    0
efectos_secundarios             0
dosis_mg                        0
vía_administración              0
contraindicaciones              0
advertencias                    0
precio_usd                      0
número_lote                     0
fecha_caducidad                 0
gravedad_efectos_secundarios    0
estado_aprobación               0
dtype: int64

In [106]:
data.duplicated().sum()

np.int64(0)

In [107]:
data.describe()

año_aprobación     dosis_mg   precio_usd
count     1436.000000  1436.000000  1436.000000
mean      2006.860028   509.637883   251.844854
std         10.167067   286.417268   142.640781
min       1990.000000    10.000000     1.210000
25%       1998.000000   270.000000   128.830000
50%       2007.000000   515.000000   255.130000
75%       2016.000000   760.000000   372.207500
max       2024.000000   990.000000   499.060000

#  

---
# <center><Font Color="#615FFF" size="8"> Preparando Datos</Font> </center>
---

In [108]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [109]:
# hecer copia profunda del dataframe
import copy
datos_ml = copy.deepcopy(data)

In [110]:
# eliminar columnas

datos_ml = datos_ml.drop(columns=['número_lote', 'fecha_caducidad'])

In [111]:
datos_ml.head(2)

nombre_medicamento   fabricante  año_aprobación clase_medicamento  \
0       Seroxetine50  AstraZeneca            1996    Antidepressant   
1        Mecoparin93  AstraZeneca            2018           Vaccine   

     indicaciones efectos_secundarios  dosis_mg vía_administración  \
0  Allergy relief     Fatigue, Nausea       260             Rectal   
1  Allergy relief              Nausea       470         Inhalation   

   contraindicaciones    advertencias  precio_usd  \
0  Bleeding disorders   Avoid alcohol      192.43   
1   Allergic reaction  Take with food      397.82   

  gravedad_efectos_secundarios estado_aprobación  
0                         Mild           Pending  
1                         Mild          Approved

In [112]:
# variables para machine

X = datos_ml.drop(columns=['estado_aprobación'])
y = datos_ml['estado_aprobación']

In [113]:
X = pd.get_dummies(X)

In [114]:
# dividir la prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [115]:
modelo = RandomForestClassifier(random_state=42,max_depth=5)
modelo.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, random_state=42)

In [116]:
y_pred = modelo.predict(X_test)

In [117]:
# Evaluación
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nReporte de Clasificación:\n", classification_report(y_test, y_pred))
print("\nMatriz de Confusión:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.3333333333333333

Reporte de Clasificación:
               precision    recall  f1-score   support

    Approved       0.40      0.04      0.08        91
     Pending       0.35      0.52      0.42       105
    Rejected       0.31      0.40      0.35        92

    accuracy                           0.33       288
   macro avg       0.35      0.32      0.28       288
weighted avg       0.35      0.33      0.29       288


Matriz de Confusión:
 [[ 4 54 33]
 [ 1 55 49]
 [ 5 50 37]]
