<a href="https://colab.research.google.com/github/r2x4/aprendiendo_machine/blob/main/machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  

----
# <center><font color="#615FFF" size="8"> Practice Machine Learning </font></center>
----

In [190]:
# llamar datos
import pandas as pd

datos = pd.read_csv('/content/realistic_drug_labels_side_effects.csv')

In [191]:
datos.shape

(1436, 15)

In [192]:
datos.sample(4)

drug_name          manufacturer  approval_year   drug_class  \
992     Fenozole66           Merck & Co.           1997  Antipyretic   
1153    Zylozole39  Moderna Therapeutics           1992   Antibiotic   
772   Rivadipine71       GlaxoSmithKline           2000   Antibiotic   
779   Amoxxetine63              Bayer AG           2016   Antifungal   

                 indications                        side_effects  dosage_mg  \
992   Inflammation reduction  Blurred vision, Insomnia, Headache        650   
1153       Psychosis control                   Dry mouth, Nausea        430   
772   Inflammation reduction                             Fatigue        690   
779         Viral infections                    Headache, Nausea        380   

     administration_route  contraindications           warnings  price_usd  \
992           Intravenous      Heart disease     Take with food     421.60   
1153        Intramuscular      Liver disease  Risk of addiction     238.43   
772               Topical  Kidney impairment  Risk of addiction     450.93   
779            Inhalation             Asthma     Take with food     333.92   

     batch_number expiry_date side_effect_severity approval_status  
992       IA182eS  2027-10-10                 Mild        Rejected  
1153      BX275Pp  2025-10-16                 Mild        Approved  
772       wI853QP  2025-12-25                 Mild         Pending  
779       fn412FG  2027-07-01               Severe         Pending

In [193]:
datos.columns

Index(['drug_name', 'manufacturer', 'approval_year', 'drug_class',
       'indications', 'side_effects', 'dosage_mg', 'administration_route',
       'contraindications', 'warnings', 'price_usd', 'batch_number',
       'expiry_date', 'side_effect_severity', 'approval_status'],
      dtype='object')

In [194]:
# renombrar la columnas

datos.columns = [
    "nombre_medicamento",
    "fabricante",
    "año_aprobación",
    "clase_medicamento",
    "indicaciones",
    "efectos_secundarios",
    "dosis_mg",
    "vía_administración",
    "contraindicaciones",
    "advertencias",
    "precio_usd",
    "número_lote",
    "fecha_caducidad",
    "gravedad_efectos_secundarios",
    "estado_aprobación"
]

In [195]:
datos.sample(4)

nombre_medicamento   fabricante  año_aprobación clase_medicamento  \
1128        Loxoparin53  AstraZeneca            2013    Antidepressant   
1098       Mecoprofen12  Pfizer Inc.            1998       Antipyretic   
679         Rivazepam35  AstraZeneca            2021    Antidepressant   
49           Daxozole11       Sanofi            2022        Antibiotic   

              indicaciones             efectos_secundarios  dosis_mg  \
1128        Allergy relief                  Blurred vision       470   
1098  Bacterial infections  Dry mouth, Headache, Dizziness       740   
679      Psychosis control              Diarrhea, Headache       240   
49       Fungal infections          Rash, Headache, Nausea       450   

     vía_administración  contraindicaciones                 advertencias  \
1128      Intramuscular            Diabetes  Use with caution in elderly   
1098            Topical       Heart disease  Use with caution in elderly   
679                Oral  Bleeding disorders            Risk of addiction   
49        Intramuscular       Liver disease         May cause drowsiness   

      precio_usd número_lote fecha_caducidad gravedad_efectos_secundarios  \
1128      468.91     wt915yv      2027-03-30                     Moderate   
1098      438.21     sO919Vp      2028-07-07                       Severe   
679       266.07     sK336WI      2028-01-24                         Mild   
49        446.13     QM274Xc      2027-01-05                       Severe   

     estado_aprobación  
1128           Pending  
1098           Pending  
679            Pending  
49            Rejected

In [196]:
# exportar a csv

datos.to_csv('datos.csv')

In [197]:
# llamar la nueva base

data = pd.read_csv('/content/datos.csv')

In [198]:
data.sample(4)

Unnamed: 0 nombre_medicamento            fabricante  año_aprobación  \
766         766         Rivazole11                Sanofi            2014   
15           15        Cefprofen42           Merck & Co.            1999   
397         397       Loxostatin62  Moderna Therapeutics            2018   
551         551        Daxozepam84       GlaxoSmithKline            2000   

     clase_medicamento     indicaciones                efectos_secundarios  \
766         Antifungal      Pain relief                           Insomnia   
15       Antipsychotic   Allergy relief  Dizziness, Insomnia, Constipation   
397  Anti-inflammatory  Fever reduction       Headache, Fatigue, Dry mouth   
551     Antidepressant      Pain relief                Dizziness, Insomnia   

     dosis_mg vía_administración contraindicaciones  \
766       960         Sublingual           Diabetes   
15        790            Topical          Pregnancy   
397       150         Sublingual             Asthma   
551       210               Oral             Asthma   

                    advertencias  precio_usd número_lote fecha_caducidad  \
766            Risk of addiction      253.78     VY323fs      2027-06-01   
15          May affect fertility       49.47     AR108jz      2026-08-07   
397  Do not discontinue abruptly      211.51     cc207cy      2027-11-05   
551  Do not discontinue abruptly      269.26     gD791Ck      2025-09-20   

    gravedad_efectos_secundarios estado_aprobación  
766                       Severe           Pending  
15                        Severe          Approved  
397                         Mild           Pending  
551                     Moderate          Rejected

In [199]:
# eliminar una columna

data = data.drop('Unnamed: 0', axis=1)

In [200]:
data.sample(4)

nombre_medicamento            fabricante  año_aprobación  \
1153         Zylozole39  Moderna Therapeutics            1992   
207        Mecocillin74           AstraZeneca            2013   
682         Cefstatin37           AstraZeneca            2017   
1258         Daxozole15  Moderna Therapeutics            2015   

     clase_medicamento       indicaciones             efectos_secundarios  \
1153        Antibiotic  Psychosis control               Dry mouth, Nausea   
207          Analgesic   Viral infections            Dry mouth, Dizziness   
682            Vaccine  Psychosis control  Headache, Dizziness, Dry mouth   
1258       Antipyretic   Viral infections                        Diarrhea   

      dosis_mg vía_administración contraindicaciones  \
1153       430      Intramuscular      Liver disease   
207        460         Inhalation           Diabetes   
682        970         Inhalation           Seizures   
1258       310               Oral           Seizures   

                     advertencias  precio_usd número_lote fecha_caducidad  \
1153            Risk of addiction      238.43     BX275Pp      2025-10-16   
207       Avoid sunlight exposure      364.35     an965iJ      2026-06-02   
682        Monitor blood pressure       61.99     OI018uh      2025-10-23   
1258  Use with caution in elderly      127.14     Ds891SU      2026-06-24   

     gravedad_efectos_secundarios estado_aprobación  
1153                         Mild          Approved  
207                      Moderate          Approved  
682                        Severe          Rejected  
1258                       Severe           Pending

In [201]:
data.dtypes

nombre_medicamento               object
fabricante                       object
año_aprobación                    int64
clase_medicamento                object
indicaciones                     object
efectos_secundarios              object
dosis_mg                          int64
vía_administración               object
contraindicaciones               object
advertencias                     object
precio_usd                      float64
número_lote                      object
fecha_caducidad                  object
gravedad_efectos_secundarios     object
estado_aprobación                object
dtype: object

In [202]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   nombre_medicamento            1436 non-null   object 
 1   fabricante                    1436 non-null   object 
 2   año_aprobación                1436 non-null   int64  
 3   clase_medicamento             1436 non-null   object 
 4   indicaciones                  1436 non-null   object 
 5   efectos_secundarios           1436 non-null   object 
 6   dosis_mg                      1436 non-null   int64  
 7   vía_administración            1436 non-null   object 
 8   contraindicaciones            1436 non-null   object 
 9   advertencias                  1436 non-null   object 
 10  precio_usd                    1436 non-null   float64
 11  número_lote                   1436 non-null   object 
 12  fecha_caducidad               1436 non-null   object 
 13  gra

In [203]:
data.isnull().sum()

nombre_medicamento              0
fabricante                      0
año_aprobación                  0
clase_medicamento               0
indicaciones                    0
efectos_secundarios             0
dosis_mg                        0
vía_administración              0
contraindicaciones              0
advertencias                    0
precio_usd                      0
número_lote                     0
fecha_caducidad                 0
gravedad_efectos_secundarios    0
estado_aprobación               0
dtype: int64

In [204]:
data.duplicated().sum()

np.int64(0)

In [205]:
data.describe()

año_aprobación     dosis_mg   precio_usd
count     1436.000000  1436.000000  1436.000000
mean      2006.860028   509.637883   251.844854
std         10.167067   286.417268   142.640781
min       1990.000000    10.000000     1.210000
25%       1998.000000   270.000000   128.830000
50%       2007.000000   515.000000   255.130000
75%       2016.000000   760.000000   372.207500
max       2024.000000   990.000000   499.060000

#  

---
# <center><Font Color="#615FFF" size="8"> Preparando Datos</Font> </center>
---

In [206]:
# biblioteca

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [207]:
# hecer copia profunda del dataframe
import copy
datos_ml = copy.deepcopy(data)

In [208]:
# eliminar columnas

datos_ml = datos_ml.drop(columns=['número_lote', 'fecha_caducidad'])

In [209]:
datos_ml.head(2)

nombre_medicamento   fabricante  año_aprobación clase_medicamento  \
0       Seroxetine50  AstraZeneca            1996    Antidepressant   
1        Mecoparin93  AstraZeneca            2018           Vaccine   

     indicaciones efectos_secundarios  dosis_mg vía_administración  \
0  Allergy relief     Fatigue, Nausea       260             Rectal   
1  Allergy relief              Nausea       470         Inhalation   

   contraindicaciones    advertencias  precio_usd  \
0  Bleeding disorders   Avoid alcohol      192.43   
1   Allergic reaction  Take with food      397.82   

  gravedad_efectos_secundarios estado_aprobación  
0                         Mild           Pending  
1                         Mild          Approved

In [210]:
# variables para machine

X = datos_ml.drop(columns=['estado_aprobación'])
y = datos_ml['estado_aprobación']

In [211]:
X = pd.get_dummies(X)

In [212]:
# dividir la prueba
X,X_test,y,y_test = train_test_split(X,y,test_size=0.15,stratify=y,random_state=42)
X_train,X_val,y_train,y_val = train_test_split(X,y,stratify=y,random_state=5)


In [213]:
modelo = RandomForestClassifier(random_state=42,max_depth=4)
modelo.fit(X_train, y_train)
print(f'La precisión del modelo train es de : {modelo.score(X_train, y_train) * 100:.2f}%')
print(f'La precisión del modelo de validación es de : {modelo.score(X_val, y_val) * 100:.2f}%')

La precisión del modelo train es de : 54.86%
La precisión del modelo de validación es de : 36.07%


In [214]:
y_pred = modelo.predict(X_test)

In [215]:
# Evaluación
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nReporte de Clasificación:\n", classification_report(y_test, y_pred))
print("\nMatriz de Confusión:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.375

Reporte de Clasificación:
               precision    recall  f1-score   support

    Approved       0.20      0.03      0.05        69
     Pending       0.38      0.80      0.52        75
    Rejected       0.38      0.26      0.31        72

    accuracy                           0.38       216
   macro avg       0.32      0.36      0.29       216
weighted avg       0.32      0.38      0.30       216


Matriz de Confusión:
 [[ 2 48 19]
 [ 3 60 12]
 [ 5 48 19]]
